# Generated by Django 5.2.6 on 2025-09-24 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_updated_on'),
    ]

    operations = [
    ]
