# Generated by Django 5.2.6 on 2025-09-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_field_2_post_field_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='field_2',
            field=models.IntegerField(default=42),
        ),
    ]
